### PR TITLE
Move FlatBuffers format classes to helper module [databricks]

### PR DESCRIPTION
**Pull request by gerashegalov**
Follow-up to #15519.

### Description

This PR moves the generated FlatBuffers format Java classes from `sql-plugin` into the Java-only `sql-plugin-format` helper module introduced by #15519.

The Java package remains `com.nvidia.spark.rapids.format`, so runtime references do not change. `sql-plugin` already depends on `sql-plugin-format` through the Spark-classified jar, and aggregator packaging includes the helper jar.

The dist packaging now promotes root-safe helper module classes by module instead of requiring every generated class package to be listed in `dist/unshimmed-common-from-single-shim.txt`:
- `dist/root-safe-module-classes.txt` lists module artifactIds whose complete class set is root-safe.
- `sql-plugin-format` is listed there, so all current and future generated format classes from that module are promoted together.
- Promotion uses class paths from the module jar but copies the matching class files from the shaded aggregator output. This preserves relocated bytecode references to `com.nvidia.shaded.spark.com.google.flatbuffers`.

The explicit allowlist still contains:
- `com/nvidia/shaded/spark/com/google/flatbuffers/*.class`

That keeps the generated format classes and their shaded FlatBuffers runtime dependency in the same classloader location after binary dedupe. Without it, the generated format classes are promoted to the dist jar root while `com.nvidia.shaded.spark.com.google.flatbuffers.Table` remains under `spark-shared`, which fails on Databricks with `NoClassDefFoundError` when the root-layout format classes load.

This is intentionally limited to generated FlatBuffers classes from `sql-plugin-format`:
- `BlockIdMeta`
- `BufferMeta`
- `BufferTransferRequest`
- `BufferTransferResponse`
- `CodecBufferDescriptor`
- `CodecType`
- `MetadataRequest`
- `MetadataResponse`
- `TableMeta`
- `TransferRequest`
- `TransferResponse`
- `TransferState`

Local validation:
- `python3 -m py_compile dist/scripts/build-unshim-parallel-world.py dist/build/package-parallel-worlds.py`
- `mvn package -pl dist -am -DskipTests -Ddist.jar.compress=false`
- `mvn -f scala2.13/pom.xml package -pl dist -am -DskipTests -Ddist.jar.compress=false`
- Jar content checks:
  - final Scala 2.12 and 2.13 dist jars contain 12 root `com/nvidia/spark/rapids/format/*.class` entries
  - final Scala 2.12 and 2.13 dist jars contain 0 `spark-shared/com/nvidia/spark/rapids/format/*.class` entries
  - final Scala 2.12 and 2.13 dist jars contain 0 shim-dir `com/nvidia/spark/rapids/format/*.class` entries
  - final Scala 2.12 and 2.13 dist jars contain 17 root `com/nvidia/shaded/spark/com/google/flatbuffers/*.class` entries
  - final Scala 2.12 and 2.13 dist jars contain 0 `spark-shared/com/nvidia/shaded/spark/com/google/flatbuffers/*.class` entries
  - `com.nvidia.spark.rapids.format.TableMeta` extends `com.nvidia.shaded.spark.com.google.flatbuffers.Table` in the final dist jar
- `git diff --check`

### Checklists

Documentation
- [ ] Updated for new or modified user-facing features or behaviors
- [x] No user-facing change

Testing
- [ ] Added or modified tests to cover new code paths
- [x] Covered by existing tests
      (Existing build/package validation for `sql-plugin-format`, `sql-plugin`, `aggregator`, and `dist` covers the moved generated classes and final jar layout.)
- [ ] Not required

Performance
- [ ] Tests ran and results are added in the PR description
- [ ] Issue filed with a link in the PR description
- [x] Not required

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by NvTimLiu — DISMISSED** [review]
This PR is mainly for the move of source code from sql-plugin/ dir to sql-plugin-format;

Other changes are build scripts optimizing, gather python scripts into functions to make the python files more readable.

From CI point of view, LGTM, +1

**Comment by gerashegalov** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
